version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: glom-chat-postgres
    environment:
      POSTGRES_DB: glom_chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d glom_chat"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    container_name: glom-chat-backend
    env_file:
      - src/server/.env.docker
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src/server/.env:/app/.env:ro  # Optional: mount .env file
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: glom-chat-network
