# fly.toml app configuration file generated for glom-chat on 2025-09-17T00:22:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'glom-chat'
primary_region = 'fra'
console_command = '/app/entrypoint.sh'

[build]
dockerfile = 'Dockerfile'

[env]
SERVER_HOST = '0.0.0.0'
SERVER_PORT = '8000'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[http_service.checks]]
interval = '15s'
timeout = '2s'
grace_period = '10s'
method = 'get'
path = '/api/ping'
protocol = 'http'

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
