name = "app"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_http = ">= 3.7.2 and < 5.0.0"
gleam_json = ">= 2.3.0 and < 4.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_time = ">= 1.4.0 and < 2.0.0"
lustre = ">= 5.3.4 and < 6.0.0"
rsvp = ">= 1.0.1 and < 2.0.0"
shared = { path = "../shared" }
lustre_websocket = ">= 0.9.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.6.5 and < 2.0.0"
lucide_lustre = ">= 2.0.1 and < 3.0.0"

[javascript]
runtime = "node"

[lucide_lustre]
output_module = "util/icons"
