name: deploy

on:
  push:
    branches:
      - master

jobs:
  # Build and deploy /client to GitHub Pages
  deploy-client:
    name: Deploy Client to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28.0"
          gleam-version: "1.12.0"
          rebar3-version: "3.25.1"

      - name: Cache Gleam build
        uses: actions/cache@v4
        with:
          path: |
            src/shared/build
            src/client/build
          key: ${{ runner.os }}-gleam-client-${{ hashFiles('src/shared/gleam.toml', 'src/client/gleam.toml', 'src/shared/manifest.toml', 'src/client/manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-gleam-client-

      # Build shared package first
      - name: Build shared package
        working-directory: src/shared
        run: |
          gleam deps download
          gleam build

      # Build client with prod config
      - name: Build client
        working-directory: src/client
        run: |
          gleam deps download
          gleam run -m lustre/dev build app --outdir=dist --minify=True
          cp index.prod.html dist/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/client/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Build and deploy /server to Fly
  deploy-server:
    name: Deploy Server to Fly.io
    runs-on: ubuntu-latest
    needs: []

    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        working-directory: .
