name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    name: Test ${{ matrix.app }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: [src/client, src/server, src/shared]

    # Run all commands from each app's root (where gleam.toml lives)
    defaults:
      run:
        working-directory: ${{ matrix.app }}

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28.0"
          gleam-version: "1.12.0"
          rebar3-version: "3.25.1"
          # elixir-version: "1"

      - name: Cache Gleam build
        uses: actions/cache@v4
        with:
          path: |
            ${{ matrix.app }}/build
          key: ${{ runner.os }}-gleam-${{ matrix.app }}-${{ hashFiles(format('{0}/gleam.toml', matrix.app), format('{0}/manifest.toml', matrix.app)) }}
          restore-keys: |
            ${{ runner.os }}-gleam-${{ matrix.app }}-

      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
